title: "\U0001D449\U0001D452\U0001D459\U0001D45C\U0001D456\U0001D451\U0001D452\U0001D462 \U0001D44A\U0001D452\U0001D44F \U0001D460\U0001D456\U0001D461\U0001D452\U0001D460"
description: ''
lang: ko
timezone: Asia/Seoul
image: assets/img/ogp.png
repo: 'https://github.com/Veloideu/veloideu.github.io'
mode: light
author:
  name: "\U0001D463\U0001D452\U0001D459\U0001D45C\U0001D456\U0001D451\U0001D452\U0001D462"
  bio: 'The Veloideu, light and dark mode support'
  username: veloideu
  github: veloideu
  twitter: veloideu
  facebook: veloideu
  email: veloideu@email.com
  avatar: /assets/img/avatar.jpg
url: 'https://veloideu.kr'
baseurl: ''
permalink: '/:title/'
google_analytics: null
fb_appid: null
collections:
  posts:
    output: true
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
defaults:
  - scope:
      path: ''
    values:
      layout: post
      comments: false
jekyll_compose:
  post_default_front_matter:
    modified: null
    tags: []
    description: null
  draft_default_front_matter:
    modified: null
    tags: []
    description: null
number_of_posts: 5
sass:
  style: compressed
include:
  - _redirects
  - .htaccess
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
